ingressClassName: portal-ingress
ingressDomain: <replaced-ingress-nginx-ip>.nip.io
image: kubebb/component-store:latest
imagePullPolicy: IfNotPresent
resources:
  limits:
    cpu: 5000m
    memory: 1280Mi
  requests:
    cpu: 500m
    memory: 512Mi
