apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: operator-serving-cert
  namespace: {{ .Values.namespace }}
spec:
  dnsNames:
  - webhook-service.{{ .Values.namespace }}.svc
  - webhook-service.{{ .Values.namespace }}.svc.cluster.local
  issuerRef:
    kind: Issuer
    name: operator-selfsigned-issuer
  secretName: webhook-server-cert