apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: pipelinerun-clusterrole
rules:
- apiGroups: ["tekton.dev"]
  resources: ["*"]
  verbs: ["*"]
- apiGroups: ["operator.tekton.dev"]
  resources: ["*"]
  verbs: ["*"]
- apiGroups: [""]
  resources: ["*"]
  verbs: ["*"]
