apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: task-rolebinding
  namespace: default
subjects:
- kind: ServiceAccount
  name: task-service-account
  namespace: default
roleRef:
  kind: ClusterRole
  name: task-clusterrole
  apiGroup: rbac.authorization.k8s.io
