apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: blockchain:common
rules:
- apiGroups:
    - ibp.com
  resources:
    - organizations
  verbs:
    - create
    - get
    - list
- apiGroups:
    - ibp.com
  resources:
    - federations
    - proposals
    - networks
    - channels
  verbs:
    - create
- apiGroups:
    - ibp.com
  resources:
    - endorsepolicies
    - chaincodebuilds
    - chaincodes
  verbs:
    - create
    - get
    - list
    - delete
- apiGroups:
    - tekton.dev
  resources:
    - pipelineruns
    - taskruns
  verbs:
    - get
    - list
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: blockchain:common
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: blockchain:common
subjects:
- kind: Group
  name: bestchains