# permissions for end users to view chaincodebuilds.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: chaincodebuild-viewer-role
rules:
- apiGroups:
  - ibp.com
  resources:
  - chaincodebuilds
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ibp.com
  resources:
  - chaincodebuilds/status
  verbs:
  - get
