# permissions for end users to view channels.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: channel-viewer-role
rules:
- apiGroups:
  - ibp.com
  resources:
  - channels
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ibp.com
  resources:
  - channels/status
  verbs:
  - get
