# permissions for end users to edit federations.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: chaincode-editor-role
rules:
- apiGroups:
  - ibp.com
  resources:
  - chaincodes
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ibp.com
  resources:
  - chaincodes/status
  verbs:
  - get
