apiVersion: apps/v1
kind: Deployment
metadata:
  name: component-store
  namespace: {{ .Release.Namespace }}
  labels:
    app: component-store
spec:
  selector:
    matchLabels:
      app: component-store
  replicas: 1
  template:
    metadata:
      labels:
        app: component-store
    spec:
      containers:
      - image: {{ .Values.image }}
        imagePullPolicy: {{ .Values.imagePullPolicy }}
        name: component-store
        ports:
        - containerPort: 8066
          protocol: TCP
        volumeMounts:
        - mountPath: /usr/src/app/packages/bff-server/configs/config.yaml
          name: component-store-bff-server-config-volume
          subPath: config.yaml
        resources: {{ toYaml .Values.resources | nindent 10 }}
      terminationGracePeriodSeconds: 30
      volumes:
      - configMap:
          defaultMode: 420
          name: component-store-bff-server-config
        name: component-store-bff-server-config-volume
