apiVersion: core.kubebb.k8s.com.cn/v1alpha1
kind: ComponentPlan
metadata:
  name: fabric-operator
  namespace: kubebb-system
spec:
  approved: true
  name: fabric-operator
  version: 0.1.0
  override:
    set:
    - namespace=kubebb-system
  component:
    name: kubebb.fabric-operator
    namespace: kubebb-system
