apiVersion: core.kubebb.k8s.com.cn/v1alpha1
kind: Repository
metadata:
  name: kubebb
  namespace: kubebb-system
  annotations: 
    core.kubebb.k8s.cn/displayname: 内核
  labels:
    kubebb.repository.source: official
spec:
  url: https://kubebb.github.io/components
  pullStategy:
    intervalSeconds: 120
    retry: 5
