apiVersion: v2
name: bc-apis
description: bc-apis is a service that provides composited APIs for the console.
type: application
version: v0.0.2
icon: https://avatars.githubusercontent.com/u/85277200
annotations:
  component-store.kubebb.k8s.com.cn/source: official
  component-store.kubebb.k8s.com.cn/license: Apache-2.0
keywords:
  - apis
  - bestchains
sources:
  - https://github.com/bestchains/bc-apis
  - https://github.com/kubebb/components
maintainers:
  - name: bjwswang
    url: https://github.com/bjwswang
  - name: Carrotzpc
    url: https://github.com/Carrotzpc
  - name: dayuy
    url: https://github.com/dayuy
