apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.fullnameOverride }}
---
{{- if eq .Values.runtimeArgs.auth "oidc"  -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ .Values.fullnameOverride }}
rules:
  - apiGroups:
      - iam.tenxcloud.com
    resources:
      - users.iam.tenxcloud.com
      - users
    verbs:
      - get
      - list
      - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ .Values.fullnameOverride }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ .Values.fullnameOverride }}
subjects:
  - kind: ServiceAccount
    name: {{ .Values.fullnameOverride }}
{{- end -}}
