apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.fullnameOverride }}
spec:
  selector:
    app: {{ .Values.fullnameOverride }}
  ports:
    - protocol: TCP
      port: 9999
      targetPort: 9999
