---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "tekton-operator.fullname" . }}
  labels:
    {{- include "tekton-operator.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "tekton-operator.operator.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "tekton-operator.operator.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - env:
            - name: SYSTEM_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              {{- if .Values.operator.operatorName }}
              value: {{- .Values.operator.operatorName }}
              {{- else }}
              {{- if .Values.openshift.enabled }}
              value: redhat-openshift-pipelines-operator
              {{- else }}
              value: tekton-operator
              {{- end }}
              {{- end }}
            - name: IMAGE_PIPELINES_PROXY
              value: {{ include "tekton-operator.webhook-proxy-image" . }}
            - name: IMAGE_JOB_PRUNER_TKN
              value: {{ .Values.pipeline.job.pruner_tkn.image }}
            - name: METRICS_DOMAIN
              value: {{ .Values.service.metricsDomain }}
            - name: VERSION
              value: {{ .Values.webhook.image.tag | default .Chart.AppVersion | quote }}
            - name: AUTOINSTALL_COMPONENTS
              value: {{ .Values.operator.autoInstallComponents | quote }}
            - name: DEFAULT_TARGET_NAMESPACE
              {{- if .Values.operator.defaultTargetNamespace }}
              value: {{ .Values.operator.defaultTargetNamespace | quote }}
              {{- else }}
              {{- if .Values.openshift.enabled }}
              value: openshift-pipelines
              {{- else }}
              value: {{ .Release.Namespace }}
              {{- end }}
              {{- end }}
            - name: CONFIG_OBSERVABILITY_NAME
              value: {{ include "tekton-operator.fullname" . }}-observability
            - name: IMAGE_PIPELINES_TEKTON_PIPELINES_CONTROLLER
              value: {{ .Values.pipeline.controller.image }}
            - name: IMAGE_PIPELINES_WEBHOOK
              value: {{ .Values.pipeline.webhook.image }}
            - name: IMAGE_PIPELINES_CONTROLLER
              value: {{ .Values.pipeline.resolvers.image }}
            - name: IMAGE_TRIGGERS_TEKTON_TRIGGERS_CONTROLLER
              value: {{ .Values.triggers.controller.image }}
            - name: IMAGE_TRIGGERS_TEKTON_TRIGGERS_CORE_INTERCEPTORS
              value: {{ .Values.triggers.interceptors.image }}
            - name: IMAGE_TRIGGERS_WEBHOOK
              value: {{ .Values.triggers.webhook.image }}
            - name: IMAGE_PIPELINES_ARG__ENTRYPOINT_IMAGE
              value: {{ .Values.pipeline.args.entrypointImage }}
            - name: IMAGE_PIPELINES_ARG__GIT_IMAGE
              value: {{ .Values.pipeline.args.gitImage}}
            - name: IMAGE_PIPELINES_ARG__KUBECONFIG_WRITER_IMAGE
              value: {{ .Values.pipeline.args.kubeconfigWriterImage}}
            - name: IMAGE_PIPELINES_ARG__NOP_IMAGE
              value: {{ .Values.pipeline.args.nopImage}}
            - name: IMAGE_PIPELINES_ARG__IMAGEDIGEST_EXPORTER_IMAGE
              value: {{ .Values.pipeline.args.imagedigestexporterImage}}
            - name: IMAGE_PIPELINES_ARG__PR_IMAGE
              value: {{ .Values.pipeline.args.pullrequestInitImage}}
            - name: IMAGE_PIPELINES_ARG__WORKINGDIRINIT_IMAGE
              value: {{ .Values.pipeline.args.workingdirinitImage}}
            - name: IMAGE_PIPELINES_ARG__GSUTIL_IMAGE
              value: {{ .Values.pipeline.args.cloudSdkImage}}
            - name: IMAGE_PIPELINES_ARG__SHELL_IMAGE
              value: {{ .Values.pipeline.args.busyboxImage}}
            - name: IMAGE_PIPELINES_ARG__SHELL_IMAGE_WIN
              value: {{ .Values.pipeline.args.powershellImage}}
          args:
            - "-controllers"
            - "tektonconfig,tektonpipeline,tektontrigger,tektonhub,tektonchain,tektonresults,tektondashboard"
            - "-unique-process-name"
            - "tekton-operator-lifecycle"
          image: {{ include "tekton-operator.operator-image" . }}
          imagePullPolicy: {{ .Values.operator.image.pullPolicy }}
          name: tekton-operator-lifecycle
          resources:
            {{- toYaml .Values.operator.resources | nindent 12 }}

        - env:
            - name: SYSTEM_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              {{- if .Values.operator.operatorName }}
              value: {{- .Values.operator.operatorName }}
              {{- else }}
              {{- if .Values.openshift.enabled }}
              value: redhat-openshift-pipelines-operator
              {{- else }}
              value: tekton-operator
              {{- end }}
              {{- end }}
            - name: IMAGE_PIPELINES_PROXY
              value: {{ include "tekton-operator.webhook-proxy-image" . }}
            - name: METRICS_DOMAIN
              value: {{ .Values.service.metricsDomain }}
            - name: VERSION
              value: {{ .Values.webhook.image.tag | default .Chart.AppVersion | quote }}
            - name: AUTOINSTALL_COMPONENTS
              value: {{ .Values.operator.autoInstallComponents | quote }}
            - name: DEFAULT_TARGET_NAMESPACE
              {{- if .Values.operator.defaultTargetNamespace }}
              value: {{ .Values.operator.defaultTargetNamespace | quote }}
              {{- else }}
              {{- if .Values.openshift.enabled }}
              value: openshift-pipelines
              {{- else }}
              value: {{ .Release.Namespace }}
              {{- end }}
              {{- end }}
            - name: CONFIG_OBSERVABILITY_NAME
              value: {{ include "tekton-operator.fullname" . }}-observability
            - name: IMAGE_PIPELINES_TEKTON_PIPELINES_CONTROLLER
              value: {{ .Values.pipeline.controller.image }}
            - name: IMAGE_PIPELINES_WEBHOOK
              value: {{ .Values.pipeline.webhook.image }}
            - name: IMAGE_PIPELINES_CONTROLLER
              value: {{ .Values.pipeline.resolvers.image }}
            - name: IMAGE_TRIGGERS_TEKTON_TRIGGERS_CONTROLLER
              value: {{ .Values.triggers.controller.image }}
            - name: IMAGE_TRIGGERS_TEKTON_TRIGGERS_CORE_INTERCEPTORS
              value: {{ .Values.triggers.interceptors.image }}
            - name: IMAGE_TRIGGERS_WEBHOOK
              value: {{ .Values.triggers.webhook.image }}
            - name: IMAGE_PIPELINES_ARG__ENTRYPOINT_IMAGE
              value: {{ .Values.pipeline.args.entrypointImage }}
            - name: IMAGE_PIPELINES_ARG__GIT_IMAGE
              value: {{ .Values.pipeline.args.gitImage}}
            - name: IMAGE_PIPELINES_ARG__KUBECONFIG_WRITER_IMAGE
              value: {{ .Values.pipeline.args.kubeconfigWriterImage}}
            - name: IMAGE_PIPELINES_ARG__NOP_IMAGE
              value: {{ .Values.pipeline.args.nopImage}}
            - name: IMAGE_PIPELINES_ARG__IMAGEDIGEST_EXPORTER_IMAGE
              value: {{ .Values.pipeline.args.imagedigestexporterImage}}
            - name: IMAGE_PIPELINES_ARG__PR_IMAGE
              value: {{ .Values.pipeline.args.pullrequestInitImage}}
            - name: IMAGE_PIPELINES_ARG__WORKINGDIRINIT_IMAGE
              value: {{ .Values.pipeline.args.workingdirinitImage}}
            - name: IMAGE_PIPELINES_ARG__GSUTIL_IMAGE
              value: {{ .Values.pipeline.args.cloudSdkImage}}
            - name: IMAGE_PIPELINES_ARG__SHELL_IMAGE
              value: {{ .Values.pipeline.args.busyboxImage}}
            - name: IMAGE_PIPELINES_ARG__SHELL_IMAGE_WIN
              value: {{ .Values.pipeline.args.powershellImage}}
          args:
            - "-controllers"
            - "tektoninstallerset"
            - "-unique-process-name"
            - "tekton-operator-cluster-operations"
          image: {{ include "tekton-operator.operator-image" . }}
          imagePullPolicy: {{ .Values.operator.image.pullPolicy }}
          name: tekton-operator-cluster-operations
          resources:
            {{- toYaml .Values.operator.resources | nindent 12 }}
      serviceAccountName: {{ include "tekton-operator.serviceAccountName" . }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "tekton-operator.fullname" . }}-webhook
  labels:
    {{- include "tekton-operator.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "tekton-operator.webhook.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "tekton-operator.webhook.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - env:
            - name: SYSTEM_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: CONFIG_LOGGING_NAME
              value: {{ include "tekton-operator.fullname" . }}-config-logging
            - name: WEBHOOK_SERVICE_NAME
              value: tekton-operator-webhook
            - name: WEBHOOK_SECRET_NAME
              value: {{ .Values.webhook.certSecret.name | default (include "tekton-operator.fullname" .) }}-webhook-certs
            - name: METRICS_DOMAIN
              value: {{ .Values.service.metricsDomain }}
          image: {{ include "tekton-operator.webhook-image" . }}
          imagePullPolicy: {{ .Values.webhook.image.pullPolicy }}
          name: {{ include "tekton-operator.operator-name" . -}}-webhook
          resources:
            {{- toYaml .Values.webhook.resources | nindent 12 }}
          ports:
            - containerPort: 8443
              name: https-webhook
      serviceAccountName: {{ include "tekton-operator.serviceAccountName" . }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
