apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: bc-apis
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: bc-apis
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: bc-apis
    spec:
      containers:
      - env:
        - name: DEFAULT_INGRESS_CLASS
          value: {{ .Values.ingressClassName }}
        - name: DEFAULT_STORAGE_CLASS
          value: {{ .Values.storageClassName }}
        - name: K8S_OIDC_PROXY_URL
          value: {{ .Values.env.k8sOIDCProxyURL }}
        - name: OIDC_SERVER_URL
          value: {{ .Values.env.OIDCServerURL }}
        - name: OIDC_SERVER_CLIENT_ID
          value: {{ .Values.env.OIDCServerClientID }}
        - name: OIDC_SERVER_CLIENT_SECRET
          value: {{ .Values.env.OIDCServerClientSecret }}
        - name: K8S_API_TIMEOUT
          value: "10"
        - name: IMAGE_NAMESPACE
          value: {{ .Values.env.imageNamespace }}
        - name: IMAGE_FABRIC_CA_TAG
          value: {{ .Values.env.imageFabricCATag }}
        - name: IAM_PROVIDER_URL
          value: {{ .Values.iamServer }}
        - name: IMAGE_FABRIC_ORDERER_TAG
          value: {{ .Values.env.imageFabricOrdererTag }}
        - name: IMAGE_FABRIC_PEER_TAG
          value: {{ .Values.env.imageFabricPeerTag }}
        - name: LOG_LEVELS
          value: {{ .Values.env.logLevels }}
        - name: OPERATOR_INGRESS_DOMAIN
          value: {{ .Values.ingressDomain }}
        - name: MINIO_ACCESS_KEY
          value: {{ .Values.env.minioAccessKey }}
        - name: MINIO_SECRET_KEY
          value: {{ .Values.env.minioSecretKey }}
        - name: MINIO_ENDPOINT
          value: {{ .Values.env.minioEndpoint }}
        image: {{ .Values.image }}
        imagePullPolicy: {{ .Values.imagePullPolicy }}
        livenessProbe:
          failureThreshold: 4
          httpGet:
            path: /health
            port: 8024
            scheme: HTTP
          initialDelaySeconds: 10
          periodSeconds: 30
          successThreshold: 1
          timeoutSeconds: 10
        name: bc-apis
        ports:
        - containerPort: 8024
          protocol: TCP
        readinessProbe:
          failureThreshold: 4
          httpGet:
            path: /health
            port: 8024
            scheme: HTTP
          initialDelaySeconds: 10
          periodSeconds: 30
          successThreshold: 1
          timeoutSeconds: 10
        resources:
          limits:
            cpu: "1"
            memory: 1Gi
          requests:
            cpu: 200m
            memory: 512Mi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /etc/localtime
          name: time-localtime
          readOnly: true
      dnsPolicy: ClusterFirst
      hostAliases:
      {{ toYaml .Values.hostAliases | nindent 8 }}
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - hostPath:
          path: /etc/localtime
          type: ""
        name: time-localtime
