apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
spec:
  ports:
  - name: http
    port: 8024
    protocol: TCP
    targetPort: 8024
  - name: ws
    port: 8025
    protocol: TCP
    targetPort: 8025
  selector:
    app: bc-apis
  sessionAffinity: None
  type: ClusterIP
