{{- if .Values.tekton.enable }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-rating
  namespace: {{ .Release.Namespace }}
binaryData:
  pipeline.yaml: |-
    {{ .Files.Get "files/rating/pipeline.yaml" | b64enc }}
  task-rbac.yaml: |-
    {{ .Files.Get "files/rating/tasks/task-rbac.yaml" | b64enc }}
  task-helm-lint.yaml: |-
    {{ .Files.Get "files/rating/tasks/task-helm-lint.yaml" | b64enc }}
  task-serviceaccount.yaml:
    {{ .Files.Get "files/rating/rbac/task-serviceaccount.yaml" | b64enc }}
  task-clusterrole.yaml: |-
    {{ .Files.Get "files/rating/rbac/task-clusterrole.yaml" | b64enc }}
  task-rolebinding.yaml: |-
    {{ .Files.Get "files/rating/rbac/task-rolebinding.yaml" | b64enc }}
  pipeline-run.yaml: |-
    {{ .Files.Get "files/rating/samples/pipeline-run.yaml" | b64enc }}
  pipelinerun-serviceaccount.yaml: |-
    {{ .Files.Get "files/rating/rbac/pipelinerun-serviceaccount.yaml" | b64enc }}
  pipelinerun-clusterrole.yaml: |-
    {{ .Files.Get "files/rating/rbac/pipelinerun-clusterrole.yaml" | b64enc }}
  pipelinerun-rolebinding.yaml: |-
    {{ .Files.Get "files/rating/rbac/pipelinerun-rolebinding.yaml" | b64enc }}
{{- end }}
