apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Release.Name }}-bc-explorer
  namespace: {{ .Release.Namespace }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ .Release.Name }}-bc-explorer
rules:
  - apiGroups:
      - ""
    resources:
      - configmaps
    verbs:
    - "*"
  - apiGroups:
      - ibp.com
    resources:
      - channels
      - channels/finalizers
      - channels/status
    verbs:
      - get
      - list
      - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ .Release.Name }}-bc-explorer
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ .Release.Name }}-bc-explorer
subjects:
  - kind: ServiceAccount
    name: {{ .Release.Name }}-bc-explorer
    namespace: {{ .Release.Namespace }}
