apiVersion: v1
kind: Secret
metadata:
  name: zhipuai
  namespace: kubebb-system
type: Opaque
data:
  apiKey: "ZmVkMDk2NWJjZTAxOTBmZjJiYzY4MWFjMzA2ZDVmM2QuZUlwN3NPWHJueG1XSnhPaw=="
---
apiVersion: arcadia.kubeagi.k8s.com.cn/v1alpha1
kind: LLM
metadata:
  name: zhipuai
  namespace: kubebb-system
spec:
  type: "zhipuai"
  url: "https://open.bigmodel.cn/api/paas/v3/model-api"
  auth: "zhipuai" # replace this with your auth secret
---
apiVersion: core.kubebb.k8s.com.cn/v1alpha1
kind: Rating
metadata:
  name: rating-with-ai
  namespace: kubebb-system
spec:
  evaluator:
    llm: zhipuai
  componentName: kubebb.kubebb-core
  pipelineParams:
    - pipelineName: kubebb-core-reliability
      dimension: "reliability"
      params:
        - name: URL
          value:
            type: string
            stringVal: https://github.com/kubebb/components/releases/download/kubebb-core-v0.1.10/kubebb-core-v0.1.10.tgz
            arrayVal: []
            objectVal: {}
        - name: COMPONENT_NAME
          value:
            stringVal: kubebb.kubebb-core
            type: string
        - name: VERSION
          value:
            stringVal: v0.1.10
            type: string
        - name: REPOSITORY_NAME
          value:
            stringVal: kubebb
            type: string
    - pipelineName: kubebb-core-security
      dimension: "security"
      params:
        - name: URL
          value:
            type: string
            stringVal: https://github.com/kubebb/components/releases/download/kubebb-core-v0.1.10/kubebb-core-v0.1.10.tgz
            arrayVal: []
            objectVal: {}
        - name: COMPONENT_NAME
          value:
            stringVal: kubebb-core
            type: string
        - name: VERSION
          value:
            stringVal: v0.1.10
            type: string
        - name: REPOSITORY_NAME
          value:
            stringVal: kubebb
            type: string
